name       : gtk-vnc
version    : 0.8.0
release    : 11
source     :
    - https://download.gnome.org/sources/gtk-vnc/0.8/gtk-vnc-0.8.0.tar.xz : 561647e093919ab0b38c4b1ea39813d5b5dc10ef290e689f4caef596a707dd57
license    : LGPL-2.1-only
component  : desktop.gnome.core
summary    : GTK VNC viewer widget
description: |
    gtk-vnc is a VNC viewer widget for GTK. It is built using coroutines allowing it to be completely asynchronous while remaining single threaded. It provides a core C library, and bindings for Python (PyGTK).
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(libsasl2)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(x11)
    - libgcrypt-devel
    - vala
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
