name       : gtk-vnc
version    : 1.3.0
release    : 20
source     :
    - https://download.gnome.org/sources/gtk-vnc/1.3/gtk-vnc-1.3.0.tar.xz : 5faaa5823b8cbe8c0b0ba1e456c4e70c4b1ae6685c9fe81a4282d98cf00a211d
license    : LGPL-2.1-only
component  : desktop.gnome.core
summary    : GTK VNC viewer widget
description: |
    gtk-vnc is a VNC viewer widget for GTK. It is built using coroutines allowing it to be completely asynchronous while remaining single threaded. It provides a core C library, and bindings for Python (PyGTK).
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(libsasl2)
    - pkgconfig(python3)
    - pkgconfig(x11)
    - libgcrypt-devel
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
