name       : gtk-vnc
version    : 0.7.1
release    : 9
source     :
    - https://download.gnome.org/sources/gtk-vnc/0.7/gtk-vnc-0.7.1.tar.xz : f34baa696615ef67666e8465b4d0ac563355e999a77d2cc42ad4625a24f7aab1
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GTK VNC viewer widget
description: |
    gtk-vnc is a VNC viewer widget for GTK. It is built using coroutines allowing it to be completely asynchronous while remaining single threaded. It provides a core C library, and bindings for Python (PyGTK).
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(libsasl2)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(x11)
    - libgcrypt-devel
    - vala
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
