name       : gtk-vnc
version    : 1.3.1
release    : 23
source     :
    - https://download.gnome.org/sources/gtk-vnc/1.3/gtk-vnc-1.3.1.tar.xz : 512763ac4e0559d0158b6682ca5dd1a3bd633f082f5e4349d7158e6b5f80f1ce
license    : LGPL-2.1-only
component  : desktop.gnome.core
summary    : GTK VNC viewer widget
description: |
    gtk-vnc is a VNC viewer widget for GTK. It is built using coroutines allowing it to be completely asynchronous while remaining single threaded. It provides a core C library, and bindings for Python (PyGTK).
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(libsasl2)
    - pkgconfig(python3)
    - pkgconfig(x11)
    - libgcrypt-devel
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
