name       : gtk-vnc
version    : 0.5.4
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gtk-vnc/0.5/gtk-vnc-0.5.4.tar.xz : 488aa97a76ce6868160699cd45d4a0ee0fe6f0ad4631737c6ddd84450f6c9ce7
license    : LGPL-2.1
summary    : GTK VNC viewer widget
description: |
    gtk-vnc is a VNC viewer widget for GTK. It is built using coroutines allowing it to be completely asynchronous while remaining single threaded. It provides a core C library, and bindings for Python (PyGTK).
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(libpulse)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsasl2)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(gnutls)
    - libgcrypt-devel
    - vala
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
